// <auto-generated />
using System;
using JobsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobsApi.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20251126075031_seedJobs")]
    partial class seedJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobsApi.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<int>("Copies")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("IntegratorUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Printed")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            Copies = 100,
                            EndTime = new DateTime(2025, 11, 19, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 70,
                            IntegratorUser = "alice",
                            JobName = "Poster Printing2",
                            JobStatus = 3,
                            MachineName = "LPT2",
                            Printed = 100,
                            StartTime = new DateTime(2025, 11, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Width = 50
                        },
                        new
                        {
                            JobId = 2,
                            Copies = 500,
                            EndTime = new DateTime(2025, 11, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 29,
                            IntegratorUser = "bob",
                            JobName = "Flyer Distribution3",
                            JobStatus = 2,
                            MachineName = "LPT3",
                            Printed = 250,
                            StartTime = new DateTime(2025, 11, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Width = 21
                        },
                        new
                        {
                            JobId = 3,
                            Copies = 200,
                            EndTime = new DateTime(2025, 11, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5,
                            IntegratorUser = "charlie",
                            JobName = "Business Cards3",
                            JobStatus = 1,
                            MachineName = "LPT2",
                            Printed = 12,
                            StartTime = new DateTime(2025, 11, 21, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Width = 9
                        },
                        new
                        {
                            JobId = 4,
                            Copies = 150,
                            EndTime = new DateTime(2025, 11, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 29,
                            IntegratorUser = "alice",
                            JobName = "Brochure Print3",
                            JobStatus = 1,
                            MachineName = "LPT3",
                            Printed = 70,
                            StartTime = new DateTime(2025, 11, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Width = 21
                        },
                        new
                        {
                            JobId = 5,
                            Copies = 20,
                            EndTime = new DateTime(2025, 11, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 90,
                            IntegratorUser = "bob",
                            JobName = "Poster Batch4",
                            JobStatus = 3,
                            MachineName = "LPT1",
                            Printed = 20,
                            StartTime = new DateTime(2025, 11, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Width = 60
                        },
                        new
                        {
                            JobId = 6,
                            Copies = 1000,
                            EndTime = new DateTime(2025, 11, 17, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5,
                            IntegratorUser = "charlie",
                            JobName = "Sticker Run4",
                            JobStatus = 1,
                            MachineName = "LPT1",
                            Printed = 700,
                            StartTime = new DateTime(2025, 11, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Width = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
